#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

mkdir log
blockMesh | tee log/blockMesh.log
$(getApplication) | tee log/$(getApplication).log
runApplication -s sigma        postProcess -func "components(sigma)"
runApplication -s singleGraph  postProcess -func singleGraph # plotting tool that can be adjusted from system folder

#------------------------------------------------------------------------------
